config/routes.rb
Rails.application.routes.draw do
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"

  get 'tasks/:id/edit', to: "tasks#edit", as: :edit_task
  patch 'tasks/:id', to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to task_path
  end

  private

  def set_task
    @tasks = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>


<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<div class="container" padding="m-3">

  <h1>My Tasks</h1>


  <ul>
    <% @tasks.each do |task| %>
      <li>
        <%= link_to task.title, task_path(task) %>
        <%= link_to "[X]", task_path(task), method: :delete %>
      </li>
    <% end %>
  </ul>


  <div>
    <%= link_to "Add a new task", tasks_new_path %>
  </div>

</div>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>



<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>


<%#= form_for(@tasks) do |f| %>
  <%#= f.label :title %>
  <%#= f.text_field :title %>

  <%#= f.label :address %>
  <%#= f.text_field :address %>

  <%#= f.submit %>
<%# end %>

<%#= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>


<div>
  <%= link_to "Edit", edit_task_path(@task)  %>
</div>